<?xml version="1.0" encoding="UTF-8"?>
<testsuite errors="1" failures="0" name="dongcai_block_test.block_write_tests.BlockWrite-20170928165251" skipped="0" tests="1" time="0.000">
	<testcase classname="dongcai_block_test.block_write_tests.BlockWrite" name="test_save_data" time="0.000">
		<error message="global name 'os' is not defined" type="NameError">
<![CDATA[Traceback (most recent call last):
  File "/home/tangr/work/f10_project/f10_new_block/src/unittest/python/dongcai_block_test/block_write_tests.py", line 20, in test_save_data
    db = self._connect_mongo()
  File "/home/tangr/work/f10_project/f10_new_block/src/unittest/python/dongcai_block_test/block_write_tests.py", line 13, in _connect_mongo
    host = os.environ.get('MYDB_PORT_27017_TCP_ADDR',"127.0.0.1")
NameError: global name 'os' is not defined
]]>		</error>
	</testcase>
	<system-out>
<![CDATA[]]>	</system-out>
	<system-err>
<![CDATA[]]>	</system-err>
</testsuite>
