<?xml version="1.0" encoding="UTF-8"?>
<testsuite errors="0" failures="1" name="dongcai_block_test.section_builder_tests.SectionBuild-20170928173913" skipped="0" tests="1" time="0.000">
	<testcase classname="dongcai_block_test.section_builder_tests.SectionBuild" name="test_section_build" time="0.000">
		<failure message="False is not true" type="AssertionError">
<![CDATA[Traceback (most recent call last):
  File "/home/tangr/work/f10_project/f10_new_block/src/unittest/python/dongcai_block_test/section_builder_tests.py", line 23, in test_section_build
    self.assertTrue(rest["StockCode"]==u'SH600639')
AssertionError: False is not true

Stdout:
('rest = ', {'StockCode': u'600639', 'Obj': u'SH600639', 'StockShortName': u'\u6d66\u4e1c\u91d1\u6865'})
]]>		</failure>
	</testcase>
	<system-out>
<![CDATA[('rest = ', {'StockCode': u'600639', 'Obj': u'SH600639', 'StockShortName': u'\u6d66\u4e1c\u91d1\u6865'})
]]>	</system-out>
	<system-err>
<![CDATA[]]>	</system-err>
</testsuite>
